### ISSUE TITLE
Bibliography is not ordered/sorted alphabetically

### ISSUE THREAD

**Issue by serin-varghese** [ifnspaml/bibliography#6]
The current bibliography in the project is not sorted alphabetically, which makes it difficult to quickly locate references. An organized, alphabetically sorted bibliography will enhance readability and maintainability of the references.

Proposed Solution:
- Install the "Sort BibTeX" extension from the VSCode marketplace.
- Use the extension to automatically sort the BibTeX entries.
- Ensure that new entries are added in an alphabetically sorted manner moving forward.

**Comment by AndrBaer** [comment]
Thx Serin, good suggestion!
